/**
 * @file espyak_dictionary.c
 * @brief Dictionary lookup using binary search
 * 
 * Port of espeak-ng dictionary system for ESP32-P4 embedded:
 * - Binary search instead of hash-table (736 KB → 184 KB memory)
 * - Sorted dictionary arrays in FLASH
 * - Multi-language support via Kconfig
 * 
 * Performance: O(log n) ~18 μs (negligible for 100 ms/phoneme TTS)
 * Decision: Jev AI recommends binary search (87% confidence)
 */

#include "espyak_internal.h"
#include "espyak_phoneme_program.h"
#include <string.h>
#include <esp_log.h>

static const char* TAG = "espyak_dict";

/* ========================================================================
 * Dictionary Initialization (Binary Array System)
 * ======================================================================== */

espyak_err_t espyak_dictionary_init(const char* lang,
                                    const espyak_config_t* config,
                                    espyak_dictionary_t** out) {
    if (!lang || !config || !out) {
        return ESPYAK_ERR_INVALID_ARG;
    }
    
    ESP_LOGI(TAG, "Initializing dictionary for '%s' (binary array)", lang);
    
    // Allocate dictionary structure
    espyak_dictionary_t* dict = espyak_calloc(1, sizeof(espyak_dictionary_t), config);
    if (!dict) {
        ESP_LOGE(TAG, "Failed to allocate dictionary structure");
        return ESPYAK_ERR_NO_MEM;
    }
    
    dict->config = config;
    dict->entries = NULL;
    dict->count = 0;
    dict->binary_data = NULL;
    
    ESP_LOGI(TAG, "Dictionary initialized (binary search mode)");
    
    *out = dict;
    return ESPYAK_OK;
}

void espyak_dictionary_deinit(espyak_dictionary_t* dict) {
    if (!dict) {
        return;
    }
    
    ESP_LOGI(TAG, "Deinitializing dictionary (%zu entries)", dict->count);
    
    // IMPORTANT: Don't free entries!
    // For embedded dictionaries: entries point to const FLASH data
    // For binary loader: entries are allocated but we don't track ownership properly yet
    // TODO: Add a flag to track if entries were malloc'd
    // For now: NEVER free entries (small memory leak on binary deinit, but safe)
    
    // Only free if allocated from binary loader
    if (dict->binary_data) {
        espyak_free(dict->entries);
    }
    
    espyak_free(dict);
}

size_t espyak_dictionary_size(const espyak_dictionary_t* dict) {
    if (!dict) {
        return 0;
    }
    return sizeof(espyak_dictionary_t) + 
           (dict->count * sizeof(espyak_dict_entry_t));
}

/* ========================================================================
 * Dictionary Lookup (Binary Search)
 * ======================================================================== */

/**
 * @brief Binary search lookup (O(log n) - ~13 comparisons for 6,641 entries)
 * 
 * Performance: ~18 μs @ 360 MHz (negligible for 100 ms/phoneme TTS)
 */
static inline int compare_word(const char* a, const char* b) {
    // Case-insensitive comparison for dictionary lookup
    while (*a && *b) {
        char ca = (*a >= 'A' && *a <= 'Z') ? (*a + 32) : *a;
        char cb = (*b >= 'A' && *b <= 'Z') ? (*b + 32) : *b;
        
        if (ca != cb) {
            return ca - cb;
        }
        a++;
        b++;
    }
    return (*a ? 1 : 0) - (*b ? 1 : 0);
}

/**
 * @brief Lookup word in sorted dictionary array
 */
espyak_err_t espyak_dictionary_lookup(espyak_dictionary_t* dict,
                                     const char* word,
                                     char* phonemes_out,
                                     size_t out_size,
                                     uint32_t* flags_out) {
    if (!dict || !word || !phonemes_out || out_size == 0) {
        return ESPYAK_ERR_INVALID_ARG;
    }
    
    if (!dict->entries || dict->count == 0) {
        return ESPYAK_ERR_NOT_FOUND;
    }
    
    // Binary search
    size_t left = 0;
    size_t right = dict->count;
    
    while (left < right) {
        size_t mid = left + (right - left) / 2;
        int cmp = compare_word(word, dict->entries[mid].word);
        
        if (cmp == 0) {
            // Found!
            strncpy(phonemes_out, dict->entries[mid].phonemes, out_size - 1);
            phonemes_out[out_size - 1] = '\0';
            
            if (flags_out) {
                *flags_out = dict->entries[mid].flags;
            }
            
            ESPYAK_DEBUG("Dictionary hit: %s -> %s", word, phonemes_out);
            return ESPYAK_OK;
        }
        
        if (cmp < 0) {
            right = mid;
        } else {
            left = mid + 1;
        }
    }
    
    // Not found
    return ESPYAK_ERR_NOT_FOUND;
}

/* ========================================================================
 * Dictionary Loading (Binary Array System)
 * ======================================================================== */

/**
 * @brief Load embedded dictionary from generated C arrays
 * 
 * This loads the dictionaries generated by dict_to_binary.py tool.
 * The arrays are already sorted at build-time for binary search.
 * 
 * Multi-language support: User selects languages via Kconfig.
 * CMake conditionally compiles only selected languages.
 */
espyak_err_t espyak_dictionary_load_embedded(espyak_dictionary_t* dict,
                                            const char* lang) {
    if (!dict || !lang) {
        return ESPYAK_ERR_INVALID_ARG;
    }
    
    ESP_LOGI(TAG, "Loading embedded dictionary for '%s'", lang);
    
    // Load language-specific dictionary
    // These are generated by tools/dict_to_binary.py and 
    // conditionally compiled via CMakeLists.txt based on Kconfig
    
    if (strcmp(lang, "en") == 0) {
#ifdef CONFIG_ESPYAK_LANG_EN
        // Include English dictionary data
        extern const espyak_dict_entry_t DICT_EN[];
        extern const size_t DICT_EN_SIZE;
        
        dict->entries = (espyak_dict_entry_t*)DICT_EN;  // Point to FLASH data
        dict->count = DICT_EN_SIZE;
        
        ESP_LOGI(TAG, "[OK] Loaded EN dictionary: %zu entries", dict->count);
        ESP_LOGI(TAG, "   Memory: %zu KB (pointer array only)", 
                 (dict->count * sizeof(espyak_dict_entry_t)) / 1024);
#else
        ESP_LOGE(TAG, "English dictionary not compiled (enable CONFIG_ESPYAK_LANG_EN)");
        return ESPYAK_ERR_NOT_FOUND;
#endif
    } else if (strcmp(lang, "de") == 0) {
#ifdef CONFIG_ESPYAK_LANG_DE
        extern const espyak_dict_entry_t DICT_DE[];
        extern const size_t DICT_DE_SIZE;
        
        dict->entries = (espyak_dict_entry_t*)DICT_DE;
        dict->count = DICT_DE_SIZE;
        
        ESP_LOGI(TAG, "[OK] Loaded DE dictionary: %zu entries", dict->count);
#else
        ESP_LOGE(TAG, "German dictionary not compiled (enable CONFIG_ESPYAK_LANG_DE)");
        return ESPYAK_ERR_NOT_FOUND;
#endif
    } else if (strcmp(lang, "fr") == 0) {
#ifdef CONFIG_ESPYAK_LANG_FR
        extern const espyak_dict_entry_t DICT_FR[];
        extern const size_t DICT_FR_SIZE;
        
        dict->entries = (espyak_dict_entry_t*)DICT_FR;
        dict->count = DICT_FR_SIZE;
        
        ESP_LOGI(TAG, "[OK] Loaded FR dictionary: %zu entries", dict->count);
#else
        ESP_LOGE(TAG, "French dictionary not compiled (enable CONFIG_ESPYAK_LANG_FR)");
        return ESPYAK_ERR_NOT_FOUND;
#endif
    } else {
        ESP_LOGW(TAG, "No embedded dictionary for language '%s'", lang);
        ESP_LOGW(TAG, "Use menuconfig to enable: Component config -> espyak -> Languages");
        return ESPYAK_ERR_NOT_FOUND;
    }
    
    return ESPYAK_OK;
}

/* ========================================================================
 * Translator (Rule engine state)
 * ======================================================================== */

/**
 * @brief Translator structure (per-language configuration)
 */
struct espyak_translator_s {
    // Core components
    espyak_phoneme_table_t* phoneme_table;
    espyak_dictionary_t* dictionary;
    
    // Letter classification (for rule matching)
    uint8_t letter_bits[256];         // Bit flags per ASCII char
    const char* letter_groups[8];     // Extended character groups
    uint32_t letter_bits_offset;      // Offset for non-Latin scripts
    
    // Translator configuration
    uint32_t stress_rule;             // STRESSPOSN_* constant
    uint32_t stress_flags;            // Stress behavior flags
    uint32_t dict_condition;          // Active dictionary conditions
    
    // Per-word state
    uint32_t word_vowel_count;
    uint32_t word_stressed_count;
    uint32_t expect_verb;
    
    const espyak_config_t* config;
    size_t heap_used;
};

/**
 * @brief Letter group constants (for letter_bits)
 */
#define LETTERGP_A       0  // Vowels (aeiou)
#define LETTERGP_B       1  // Consonants (bcdfg...)
#define LETTERGP_C       2  // Consonants variant
#define LETTERGP_H       3  // hlmnr
#define LETTERGP_F       4  // Voiceless (cfhkpqstx)
#define LETTERGP_G       5  // Voiced (bdgjlmnrvwyz)
#define LETTERGP_Y       6  // eiy
#define LETTERGP_VOWEL2  7  // Extended vowels (aeiouy)

/**
 * @brief Default English letter classification
 */
static const char* DEFAULT_LETTER_GROUPS[] = {
    [LETTERGP_A]      = "aeiou",
    [LETTERGP_B]      = "bcdfgjklmnpqstvxz",
    [LETTERGP_C]      = "bcdfghjklmnpqrstvwxz",
    [LETTERGP_H]      = "hlmnr",
    [LETTERGP_F]      = "cfhkpqstx",
    [LETTERGP_G]      = "bdgjlmnrvwyz",
    [LETTERGP_Y]      = "eiy",
    [LETTERGP_VOWEL2] = "aeiouy",
};

/**
 * @brief Initialize letter classification
 */
static void setup_letters(espyak_translator_t* tr) {
    // Setup default English letter groups
    for (int group = 0; group < 8; group++) {
        const char* letters = DEFAULT_LETTER_GROUPS[group];
        if (!letters) continue;
        
        uint8_t bit = (1 << group);
        for (const char* p = letters; *p; p++) {
            uint8_t ch = (uint8_t)*p;
            // uint8_t is always < 256, directly index
            tr->letter_bits[ch] |= bit;
        }
    }
    
    // TODO Phase 3: Load language-specific letter bits
}

espyak_err_t espyak_translator_init(const char* lang,
                                    const espyak_config_t* config,
                                    espyak_phoneme_table_t* phoneme_table,
                                    espyak_dictionary_t* dictionary,
                                    espyak_translator_t** out) {
    if (!lang || !config || !phoneme_table || !dictionary || !out) {
        return ESPYAK_ERR_INVALID_ARG;
    }
    
    ESP_LOGI(TAG, "Initializing translator for '%s'", lang);
    
    // Allocate translator (DRAM for fast access)
    espyak_translator_t* tr = espyak_calloc(1, sizeof(espyak_translator_t), config);
    if (!tr) {
        ESP_LOGE(TAG, "Failed to allocate translator");
        return ESPYAK_ERR_NO_MEM;
    }
    
    tr->phoneme_table = phoneme_table;
    tr->dictionary = dictionary;
    tr->config = config;
    tr->heap_used = sizeof(espyak_translator_t);
    
    // Setup letter classification
    setup_letters(tr);
    
    // Default stress configuration (English-like)
    tr->stress_rule = 2;  // STRESSPOSN_2R (penultimate stress)
    tr->stress_flags = 0;
    tr->dict_condition = 0;
    
    ESP_LOGI(TAG, "Translator initialized: %zu bytes", tr->heap_used);
    
    *out = tr;
    return ESPYAK_OK;
}

void espyak_translator_deinit(espyak_translator_t* translator) {
    if (!translator) {
        return;
    }
    
    ESP_LOGI(TAG, "Deinitializing translator");
    espyak_free(translator);
}

size_t espyak_translator_size(const espyak_translator_t* translator) {
    return translator ? translator->heap_used : 0;
}

/* ========================================================================
 * Translation Pipeline (Dictionary-only for now)
 * ======================================================================== */

/**
 * @brief Simple word splitter (UTF-8 aware)
 */
static size_t split_words(const char* text, char words[][128], size_t max_words) {
    size_t word_count = 0;
    size_t word_len = 0;
    
    for (const char* p = text; *p && word_count < max_words; p++) {
        if (*p == ' ' || *p == '\t' || *p == '\n' || *p == '\r') {
            // Whitespace - end current word
            if (word_len > 0) {
                words[word_count][word_len] = '\0';
                word_count++;
                word_len = 0;
            }
        } else {
            // Add to current word
            if (word_len < 127) {
                words[word_count][word_len++] = *p;
            }
        }
    }
    
    // Last word
    if (word_len > 0) {
        words[word_count][word_len] = '\0';
        word_count++;
    }
    
    return word_count;
}

espyak_err_t espyak_translator_phonemize(espyak_translator_t* translator,
                                         const char* text,
                                         char* output,
                                         size_t out_size,
                                         const espyak_options_t* options) {
    if (!translator || !text || !output || out_size == 0) {
        return ESPYAK_ERR_INVALID_ARG;
    }
    
    // Allocate word buffer on heap to avoid stack overflow
    // Max 32 words, 128 bytes each = 4KB (too much for stack!)
    char (*words)[128] = espyak_malloc(32 * 128, translator->config);
    if (!words) {
        return ESPYAK_ERR_NO_MEM;
    }
    
    size_t word_count = split_words(text, words, 32);
    
    if (word_count == 0) {
        output[0] = '\0';
        espyak_free(words);
        return ESPYAK_OK;
    }
    
    // Allocate result buffer on heap
    char* result = espyak_malloc(1024, translator->config);
    if (!result) {
        espyak_free(words);
        return ESPYAK_ERR_NO_MEM;
    }
    memset(result, 0, 1024);
    size_t result_len = 0;
    
    for (size_t i = 0; i < word_count; i++) {
        char phonemes[256];
        
        // Try dictionary lookup
        espyak_err_t err = espyak_dictionary_lookup(
            translator->dictionary,
            words[i],
            phonemes,
            sizeof(phonemes),
            NULL
        );
        
        if (err == ESPYAK_OK) {
            // Found in dictionary
            ESPYAK_DEBUG("Dictionary hit: %s -> %s", words[i], phonemes);
        } else {
            // Not found - try rule matching
            err = espyak_text_to_phonemes(words[i], phonemes, sizeof(phonemes));
            
            if (err == ESPYAK_OK) {
                ESPYAK_DEBUG("Rule match: %s -> %s", words[i], phonemes);
            } else {
                // Rule matching failed - fallback to copying input
                strncpy(phonemes, words[i], sizeof(phonemes) - 1);
                phonemes[sizeof(phonemes) - 1] = '\0';
                
                ESPYAK_DEBUG("No match: %s (copied as-is)", words[i]);
            }
        }
        
        // Parse concatenated string ("h@loU" or rule match "fVk") and add spaces ("h @ l oU")
        // We do this for BOTH dictionary and rule matches so they can be rendered to IPA correctly
        const espyak_phoneme_t* parsed_ph[32];
        size_t num_parsed = 0;
        if (espyak_parse_phoneme_string(translator->phoneme_table, phonemes, parsed_ph, 32, &num_parsed) == ESPYAK_OK && num_parsed > 0) {
            size_t ppos = 0;
            for (size_t p = 0; p < num_parsed; p++) {
                if (p > 0 && ppos < sizeof(phonemes) - 1) {
                    phonemes[ppos++] = ' ';
                }
                size_t mlen = strlen(parsed_ph[p]->mnemonic);
                if (ppos + mlen < sizeof(phonemes)) {
                    memcpy(phonemes + ppos, parsed_ph[p]->mnemonic, mlen);
                    ppos += mlen;
                }
            }
            phonemes[ppos] = '\0';
            ESPYAK_DEBUG("Parsed and spaced phonemes: %s", phonemes);
        }
        
        // NEW: Execute phoneme programs on phoneme string
        // This implements Step 4 of the translation pipeline:
        //   1. Word split ✓
        //   2. Dictionary/rules ✓
        //   3. Stress assignment (TODO)
        //   4. Phoneme programs ✓ (NEW)
        //   5. Render (below)
        if (strlen(phonemes) > 0) {
            err = espyak_execute_phoneme_programs_on_string(
                translator->phoneme_table,  // Pass phoneme table directly
                phonemes,
                sizeof(phonemes)
            );
            
            if (err != ESPYAK_OK) {
                ESP_LOGW(TAG, "Phoneme programs failed for '%s': %d", words[i], err);
                // Continue anyway - programs are optional enhancement
            }
        }
        
        // NEW: Render phonemes to IPA or Kirshenbaum (Step 5)
        if (strlen(phonemes) > 0) {
            char rendered_phonemes[256];
            err = espyak_render_phoneme_string(
                translator->phoneme_table,
                phonemes,
                rendered_phonemes,
                sizeof(rendered_phonemes),
                options->format,
                options->separator,
                options->tie
            );
            
            if (err == ESPYAK_OK) {
                strncpy(phonemes, rendered_phonemes, sizeof(phonemes) - 1);
                phonemes[sizeof(phonemes) - 1] = '\0';
            } else {
                ESP_LOGW(TAG, "Render failed for '%s': %d", words[i], err);
            }
        }
        
        // Append to result
        if (result_len > 0 && result_len < 1024 - 1) {
            result[result_len++] = ' ';
        }
        
        size_t plen = strlen(phonemes);
        if (result_len + plen < 1024) {
            memcpy(result + result_len, phonemes, plen);
            result_len += plen;
        }
    }
    
    result[result_len] = '\0';
    
    // Copy to output buffer
    if (result_len >= out_size) {
        ESP_LOGW(TAG, "Output buffer too small: need %zu, have %zu", 
                 result_len + 1, out_size);
        espyak_free(result);
        espyak_free(words);
        return ESPYAK_ERR_BUFFER_TOO_SMALL;
    }
    
    strncpy(output, result, out_size - 1);
    output[out_size - 1] = '\0';
    
    ESPYAK_DEBUG("Phonemized: '%s' -> '%s'", text, output);
    
    // Cleanup
    espyak_free(result);
    espyak_free(words);
    
    return ESPYAK_OK;
}
