/**
 * @file espyak_phsource_data.c
 * @brief Embedded phsource/phonemes data (MINIMAL TEST SET)
 * 
 * Hand-crafted minimal phoneme set for testing:
 * - Basic vowels: @, a, e, i, o, u
 * - Consonants: h, l, r, w, j, m, n, b, d, g, p, t, k, f, v, s, z, S, Z, T, D
 * - Affricates: tS, dZ
 * - Long vowels: i:, u:, A:, O:
 * - English vowels: I, V, U
 * - Diphthongs: aI, aU, OI
 */

#include <stddef.h>

// MINIMAL TEST DATA
const char espyak_phsource_phonemes_test[] = 
  "// This is the master phoneme file.\n"
  "\n"
  "phoneme %  //  Unstressed\n"
  "  stress\n"
  "  stress_type 1\n"
  "endphoneme\n"
  "\n"
  "phoneme '   //  Primary stress\n"
  "  stress\n"
  "  stress_type 4\n"
  "endphoneme\n"
  "\n"
  "phoneme ||  //   End Word\n"
  "  pause\n"
  "endphoneme\n"
  "\n"
  "phoneme _  //  Short pause\n"
  "  pause\n"
  "  starttype _ endtype _\n"
  "  length 25\n"
  "endphoneme\n"
  "\n"
  "phoneme @    //  Schwa\n"
  "  vwl   starttype #@  endtype #@\n"
  "  unstressed\n"
  "  length 140\n"
  "endphoneme\n"
  "\n"
  "phoneme a\n"
  "  vwl starttype #a endtype #a\n"
  "  length 180\n"
  "endphoneme\n"
  "\n"
  "phoneme e\n"
  "  vwl starttype #e endtype #e\n"
  "  length 170\n"
  "endphoneme\n"
  "\n"
  "phoneme i\n"
  "  vwl starttype #i endtype #i\n"
  "  length 170\n"
  "endphoneme\n"
  "\n"
  "phoneme o\n"
  "  vwl starttype #o endtype #o\n"
  "  length 170\n"
  "endphoneme\n"
  "\n"
  "phoneme u\n"
  "  vwl starttype #u endtype #u\n"
  "  length 170\n"
  "endphoneme\n"
  "\n"
  "// Consonants\n"
  "\n"
  "phoneme h\n"
  "  vls glt apr\n"
  "  lengthmod 3\n"
  "endphoneme\n"
  "\n"
  "phoneme l\n"
  "  liquid\n"
  "  lengthmod 7\n"
  "endphoneme\n"
  "\n"
  "phoneme r\n"
  "  liquid rhotic\n"
  "  lengthmod 7\n"
  "endphoneme\n"
  "\n"
  "phoneme w\n"
  "  liquid\n"
  "  lengthmod 7\n"
  "  starttype #u\n"
  "endphoneme\n"
  "\n"
  "phoneme j\n"
  "  liquid pal starttype #i\n"
  "  lengthmod 7\n"
  "endphoneme\n"
  "\n"
  "phoneme m\n"
  "  vcd blb nas\n"
  "  lengthmod 4\n"
  "endphoneme\n"
  "\n"
  "phoneme n\n"
  "  vcd alv nas\n"
  "  lengthmod 4\n"
  "endphoneme\n"
  "\n"
  "phoneme b\n"
  "  vcd blb stp\n"
  "  lengthmod 5\n"
  "endphoneme\n"
  "\n"
  "phoneme d\n"
  "  vcd alv stp\n"
  "  lengthmod 5\n"
  "endphoneme\n"
  "\n"
  "phoneme g\n"
  "  vcd vel stp\n"
  "  lengthmod 5\n"
  "endphoneme\n"
  "\n"
  "phoneme p\n"
  "  vls blb stp\n"
  "  lengthmod 2\n"
  "endphoneme\n"
  "\n"
  "phoneme t\n"
  "  vls alv stp\n"
  "  lengthmod 2\n"
  "endphoneme\n"
  "\n"
  "phoneme k\n"
  "  vls vel stp\n"
  "  lengthmod 2\n"
  "endphoneme\n"
  "\n"
  "phoneme f\n"
  "  vls lbd frc\n"
  "  lengthmod 3\n"
  "endphoneme\n"
  "\n"
  "phoneme v\n"
  "  vcd lbd frc\n"
  "  lengthmod 6\n"
  "endphoneme\n"
  "\n"
  "phoneme s\n"
  "  vls alv frc sib\n"
  "  lengthmod 3\n"
  "endphoneme\n"
  "\n"
  "phoneme z\n"
  "  vcd alv frc sib\n"
  "  lengthmod 6\n"
  "endphoneme\n"
  "\n"
  "phoneme S\n"
  "  vls pla frc sib\n"
  "  lengthmod 3\n"
  "endphoneme\n"
  "\n"
  "phoneme Z\n"
  "  vcd pla frc sib\n"
  "  lengthmod 6\n"
  "endphoneme\n"
  "\n"
  "phoneme T\n"
  "  vls dnt frc\n"
  "  lengthmod 3\n"
  "endphoneme\n"
  "\n"
  "phoneme D\n"
  "  vcd dnt frc\n"
  "  lengthmod 6\n"
  "endphoneme\n"
  "\n"
  "phoneme tS\n"
  "  vls pla afr sib\n"
  "  lengthmod 2\n"
  "endphoneme\n"
  "\n"
  "phoneme dZ\n"
  "  vcd pla afr sib\n"
  "  lengthmod 5\n"
  "endphoneme\n"
  "\n"
  "// Vowels with length markers\n"
  "\n"
  "phoneme i:\n"
  "  vwl starttype #i endtype #i\n"
  "  length 200\n"
  "endphoneme\n"
  "\n"
  "phoneme u:\n"
  "  vwl starttype #u endtype #u\n"
  "  length 200\n"
  "endphoneme\n"
  "\n"
  "phoneme A:\n"
  "  vwl starttype #a endtype #a\n"
  "  length 210\n"
  "endphoneme\n"
  "\n"
  "phoneme O:\n"
  "  vwl starttype #o endtype #o\n"
  "  length 210\n"
  "endphoneme\n"
  "\n"
  "// Common English vowels\n"
  "\n"
  "phoneme I\n"
  "  vwl starttype #i endtype #i\n"
  "  unstressed\n"
  "  length 130\n"
  "endphoneme\n"
  "\n"
  "phoneme V\n"
  "  vwl starttype #@ endtype #@\n"
  "  length 140\n"
  "endphoneme\n"
  "\n"
  "phoneme U\n"
  "  vwl starttype #u endtype #u\n"
  "  length 150\n"
  "endphoneme\n"
  "\n"
  "phoneme O\n"
  "  vwl starttype #o endtype #o\n"
  "  length 170\n"
  "endphoneme\n"
  "\n"
  "phoneme E\n"
  "  vwl starttype #e endtype #e\n"
  "  length 150\n"
  "endphoneme\n"
  "\n"
  "phoneme 3\n"
  "  vwl starttype #@ endtype #@\n"
  "  length 180\n"
  "endphoneme\n"
  "\n"
  "phoneme N\n"
  "  vcd vel nas\n"
  "  lengthmod 4\n"
  "endphoneme\n"
  "\n"
  "// Diphthongs\n"
  "\n"
  "phoneme @U\n"
  "  vwl starttype #@ endtype #u\n"
  "  length 220\n"
  "endphoneme\n"
  "\n"
  "phoneme oU\n"
  "  vwl starttype #o endtype #u\n"
  "  length 220\n"
  "endphoneme\n"
  "\n"
  "phoneme eI\n"
  "  vwl starttype #e endtype #i\n"
  "  length 220\n"
  "endphoneme\n"
  "\n"
  "phoneme aI\n"
  "  vwl starttype #a endtype #i\n"
  "  length 220\n"
  "endphoneme\n"
  "\n"
  "phoneme aU\n"
  "  vwl starttype #a endtype #u\n"
  "  length 220\n"
  "endphoneme\n"
  "\n"
  "phoneme OI\n"
  "  vwl starttype #o endtype #i\n"
  "  length 230\n"
  "endphoneme\n"
  "\n"
;

const size_t espyak_phsource_phonemes_test_size = sizeof(espyak_phsource_phonemes_test);
