/**
 * @file all_languages.h
 * @brief Unified header for all language dictionaries
 * 
 * Auto-generated by extract_all_languages.py
 */

#ifndef ESPYAK_ALL_LANGUAGES_H
#define ESPYAK_ALL_LANGUAGES_H

#include <stdint.h>

typedef struct {
    const char* word;
    const char* phonemes;
    uint32_t flags;
} espyak_dict_entry_embedded_t;

// af: 3,190 entries
extern const espyak_dict_entry_embedded_t DICT_AF[];
extern const size_t DICT_AF_SIZE;

// am: 1,670 entries
extern const espyak_dict_entry_embedded_t DICT_AM[];
extern const size_t DICT_AM_SIZE;

// an: 476 entries
extern const espyak_dict_entry_embedded_t DICT_AN[];
extern const size_t DICT_AN_SIZE;

// ar: 31,973 entries
extern const espyak_dict_entry_embedded_t DICT_AR[];
extern const size_t DICT_AR_SIZE;

// as: 207 entries
extern const espyak_dict_entry_embedded_t DICT_AS[];
extern const size_t DICT_AS_SIZE;

// az: 1,722 entries
extern const espyak_dict_entry_embedded_t DICT_AZ[];
extern const size_t DICT_AZ_SIZE;

// ba: 70 entries
extern const espyak_dict_entry_embedded_t DICT_BA[];
extern const size_t DICT_BA_SIZE;

// be: 77 entries
extern const espyak_dict_entry_embedded_t DICT_BE[];
extern const size_t DICT_BE_SIZE;

// bg: 4,655 entries
extern const espyak_dict_entry_embedded_t DICT_BG[];
extern const size_t DICT_BG_SIZE;

// bn: 2,009 entries
extern const espyak_dict_entry_embedded_t DICT_BN[];
extern const size_t DICT_BN_SIZE;

// bpy: 179 entries
extern const espyak_dict_entry_embedded_t DICT_BPY[];
extern const size_t DICT_BPY_SIZE;

// bs: 2,182 entries
extern const espyak_dict_entry_embedded_t DICT_BS[];
extern const size_t DICT_BS_SIZE;

// ca: 14,204 entries
extern const espyak_dict_entry_embedded_t DICT_CA[];
extern const size_t DICT_CA_SIZE;

// cmn: 5,499 entries
extern const espyak_dict_entry_embedded_t DICT_CMN[];
extern const size_t DICT_CMN_SIZE;

// cs: 2,028 entries
extern const espyak_dict_entry_embedded_t DICT_CS[];
extern const size_t DICT_CS_SIZE;

// cy: 1,798 entries
extern const espyak_dict_entry_embedded_t DICT_CY[];
extern const size_t DICT_CY_SIZE;

// da: 12,589 entries
extern const espyak_dict_entry_embedded_t DICT_DA[];
extern const size_t DICT_DA_SIZE;

// de: 2,672 entries
extern const espyak_dict_entry_embedded_t DICT_DE[];
extern const size_t DICT_DE_SIZE;

// el: 2,001 entries
extern const espyak_dict_entry_embedded_t DICT_EL[];
extern const size_t DICT_EL_SIZE;

// en: 6,641 entries
extern const espyak_dict_entry_embedded_t DICT_EN[];
extern const size_t DICT_EN_SIZE;

// eo: 235 entries
extern const espyak_dict_entry_embedded_t DICT_EO[];
extern const size_t DICT_EO_SIZE;

// es: 1,999 entries
extern const espyak_dict_entry_embedded_t DICT_ES[];
extern const size_t DICT_ES_SIZE;

// et: 1,934 entries
extern const espyak_dict_entry_embedded_t DICT_ET[];
extern const size_t DICT_ET_SIZE;

// eu: 1,829 entries
extern const espyak_dict_entry_embedded_t DICT_EU[];
extern const size_t DICT_EU_SIZE;

// fa: 14,887 entries
extern const espyak_dict_entry_embedded_t DICT_FA[];
extern const size_t DICT_FA_SIZE;

// fi: 1,968 entries
extern const espyak_dict_entry_embedded_t DICT_FI[];
extern const size_t DICT_FI_SIZE;

// fo: 228,010 entries
extern const espyak_dict_entry_embedded_t DICT_FO[];
extern const size_t DICT_FO_SIZE;

// fr: 2,424 entries
extern const espyak_dict_entry_embedded_t DICT_FR[];
extern const size_t DICT_FR_SIZE;

// ga: 1,874 entries
extern const espyak_dict_entry_embedded_t DICT_GA[];
extern const size_t DICT_GA_SIZE;

// gd: 1,739 entries
extern const espyak_dict_entry_embedded_t DICT_GD[];
extern const size_t DICT_GD_SIZE;

// gn: 147 entries
extern const espyak_dict_entry_embedded_t DICT_GN[];
extern const size_t DICT_GN_SIZE;

// grc: 21 entries
extern const espyak_dict_entry_embedded_t DICT_GRC[];
extern const size_t DICT_GRC_SIZE;

// gu: 1,811 entries
extern const espyak_dict_entry_embedded_t DICT_GU[];
extern const size_t DICT_GU_SIZE;

// hak: 22 entries
extern const espyak_dict_entry_embedded_t DICT_HAK[];
extern const size_t DICT_HAK_SIZE;

// haw: 99 entries
extern const espyak_dict_entry_embedded_t DICT_HAW[];
extern const size_t DICT_HAW_SIZE;

// he: 264 entries
extern const espyak_dict_entry_embedded_t DICT_HE[];
extern const size_t DICT_HE_SIZE;

// hi: 1,951 entries
extern const espyak_dict_entry_embedded_t DICT_HI[];
extern const size_t DICT_HI_SIZE;

// hr: 2,186 entries
extern const espyak_dict_entry_embedded_t DICT_HR[];
extern const size_t DICT_HR_SIZE;

// ht: 50 entries
extern const espyak_dict_entry_embedded_t DICT_HT[];
extern const size_t DICT_HT_SIZE;

// hu: 5,543 entries
extern const espyak_dict_entry_embedded_t DICT_HU[];
extern const size_t DICT_HU_SIZE;

// hy: 1,757 entries
extern const espyak_dict_entry_embedded_t DICT_HY[];
extern const size_t DICT_HY_SIZE;

// ia: 15,485 entries
extern const espyak_dict_entry_embedded_t DICT_IA[];
extern const size_t DICT_IA_SIZE;

// id: 1,771 entries
extern const espyak_dict_entry_embedded_t DICT_ID[];
extern const size_t DICT_ID_SIZE;

// io: 50 entries
extern const espyak_dict_entry_embedded_t DICT_IO[];
extern const size_t DICT_IO_SIZE;

// is: 1,951 entries
extern const espyak_dict_entry_embedded_t DICT_IS[];
extern const size_t DICT_IS_SIZE;

// it: 11,030 entries
extern const espyak_dict_entry_embedded_t DICT_IT[];
extern const size_t DICT_IT_SIZE;

// ja: 1,662 entries
extern const espyak_dict_entry_embedded_t DICT_JA[];
extern const size_t DICT_JA_SIZE;

// jbo: 85 entries
extern const espyak_dict_entry_embedded_t DICT_JBO[];
extern const size_t DICT_JBO_SIZE;

// ka: 1,783 entries
extern const espyak_dict_entry_embedded_t DICT_KA[];
extern const size_t DICT_KA_SIZE;

// kaa: 26 entries
extern const espyak_dict_entry_embedded_t DICT_KAA[];
extern const size_t DICT_KAA_SIZE;

// kk: 51 entries
extern const espyak_dict_entry_embedded_t DICT_KK[];
extern const size_t DICT_KK_SIZE;

// kl: 82 entries
extern const espyak_dict_entry_embedded_t DICT_KL[];
extern const size_t DICT_KL_SIZE;

// kn: 1,897 entries
extern const espyak_dict_entry_embedded_t DICT_KN[];
extern const size_t DICT_KN_SIZE;

// ko: 1,771 entries
extern const espyak_dict_entry_embedded_t DICT_KO[];
extern const size_t DICT_KO_SIZE;

// kok: 188 entries
extern const espyak_dict_entry_embedded_t DICT_KOK[];
extern const size_t DICT_KOK_SIZE;

// ku: 106 entries
extern const espyak_dict_entry_embedded_t DICT_KU[];
extern const size_t DICT_KU_SIZE;

// ky: 1,764 entries
extern const espyak_dict_entry_embedded_t DICT_KY[];
extern const size_t DICT_KY_SIZE;

// la: 202 entries
extern const espyak_dict_entry_embedded_t DICT_LA[];
extern const size_t DICT_LA_SIZE;

// lb: 35,661 entries
extern const espyak_dict_entry_embedded_t DICT_LB[];
extern const size_t DICT_LB_SIZE;

// lfn: 126 entries
extern const espyak_dict_entry_embedded_t DICT_LFN[];
extern const size_t DICT_LFN_SIZE;

// lt: 1,803 entries
extern const espyak_dict_entry_embedded_t DICT_LT[];
extern const size_t DICT_LT_SIZE;

// lv: 2,380 entries
extern const espyak_dict_entry_embedded_t DICT_LV[];
extern const size_t DICT_LV_SIZE;

// mi: 14 entries
extern const espyak_dict_entry_embedded_t DICT_MI[];
extern const size_t DICT_MI_SIZE;

// mk: 1,814 entries
extern const espyak_dict_entry_embedded_t DICT_MK[];
extern const size_t DICT_MK_SIZE;

// ml: 1,804 entries
extern const espyak_dict_entry_embedded_t DICT_ML[];
extern const size_t DICT_ML_SIZE;

// mr: 1,872 entries
extern const espyak_dict_entry_embedded_t DICT_MR[];
extern const size_t DICT_MR_SIZE;

// ms: 2,330 entries
extern const espyak_dict_entry_embedded_t DICT_MS[];
extern const size_t DICT_MS_SIZE;

// mt: 207 entries
extern const espyak_dict_entry_embedded_t DICT_MT[];
extern const size_t DICT_MT_SIZE;

// mto: 182 entries
extern const espyak_dict_entry_embedded_t DICT_MTO[];
extern const size_t DICT_MTO_SIZE;

// my: 1,647 entries
extern const espyak_dict_entry_embedded_t DICT_MY[];
extern const size_t DICT_MY_SIZE;

// nci: 16 entries
extern const espyak_dict_entry_embedded_t DICT_NCI[];
extern const size_t DICT_NCI_SIZE;

// ne: 1,828 entries
extern const espyak_dict_entry_embedded_t DICT_NE[];
extern const size_t DICT_NE_SIZE;

// nl: 3,447 entries
extern const espyak_dict_entry_embedded_t DICT_NL[];
extern const size_t DICT_NL_SIZE;

// no: 232 entries
extern const espyak_dict_entry_embedded_t DICT_NO[];
extern const size_t DICT_NO_SIZE;

// nog: 37 entries
extern const espyak_dict_entry_embedded_t DICT_NOG[];
extern const size_t DICT_NOG_SIZE;

// om: 85 entries
extern const espyak_dict_entry_embedded_t DICT_OM[];
extern const size_t DICT_OM_SIZE;

// or: 1,821 entries
extern const espyak_dict_entry_embedded_t DICT_OR[];
extern const size_t DICT_OR_SIZE;

// pa: 1,828 entries
extern const espyak_dict_entry_embedded_t DICT_PA[];
extern const size_t DICT_PA_SIZE;

// pap: 83 entries
extern const espyak_dict_entry_embedded_t DICT_PAP[];
extern const size_t DICT_PAP_SIZE;

// pl: 4,411 entries
extern const espyak_dict_entry_embedded_t DICT_PL[];
extern const size_t DICT_PL_SIZE;

// pt: 3,300 entries
extern const espyak_dict_entry_embedded_t DICT_PT[];
extern const size_t DICT_PT_SIZE;

// py: 106 entries
extern const espyak_dict_entry_embedded_t DICT_PY[];
extern const size_t DICT_PY_SIZE;

// qdb: 168 entries
extern const espyak_dict_entry_embedded_t DICT_QDB[];
extern const size_t DICT_QDB_SIZE;

// qu: 76 entries
extern const espyak_dict_entry_embedded_t DICT_QU[];
extern const size_t DICT_QU_SIZE;

// quc: 10 entries
extern const espyak_dict_entry_embedded_t DICT_QUC[];
extern const size_t DICT_QUC_SIZE;

// qya: 38 entries
extern const espyak_dict_entry_embedded_t DICT_QYA[];
extern const size_t DICT_QYA_SIZE;

// ro: 3,719 entries
extern const espyak_dict_entry_embedded_t DICT_RO[];
extern const size_t DICT_RO_SIZE;

// ru: 1,853 entries
extern const espyak_dict_entry_embedded_t DICT_RU[];
extern const size_t DICT_RU_SIZE;

// sd: 1,827 entries
extern const espyak_dict_entry_embedded_t DICT_SD[];
extern const size_t DICT_SD_SIZE;

// shn: 4,175 entries
extern const espyak_dict_entry_embedded_t DICT_SHN[];
extern const size_t DICT_SHN_SIZE;

// si: 1,790 entries
extern const espyak_dict_entry_embedded_t DICT_SI[];
extern const size_t DICT_SI_SIZE;

// sjn: 21 entries
extern const espyak_dict_entry_embedded_t DICT_SJN[];
extern const size_t DICT_SJN_SIZE;

// sk: 1,977 entries
extern const espyak_dict_entry_embedded_t DICT_SK[];
extern const size_t DICT_SK_SIZE;

// sl: 1,823 entries
extern const espyak_dict_entry_embedded_t DICT_SL[];
extern const size_t DICT_SL_SIZE;

// smj: 2,603 entries
extern const espyak_dict_entry_embedded_t DICT_SMJ[];
extern const size_t DICT_SMJ_SIZE;

// sq: 1,765 entries
extern const espyak_dict_entry_embedded_t DICT_SQ[];
extern const size_t DICT_SQ_SIZE;

// sr: 2,115 entries
extern const espyak_dict_entry_embedded_t DICT_SR[];
extern const size_t DICT_SR_SIZE;

// sv: 1,960 entries
extern const espyak_dict_entry_embedded_t DICT_SV[];
extern const size_t DICT_SV_SIZE;

// sw: 1,803 entries
extern const espyak_dict_entry_embedded_t DICT_SW[];
extern const size_t DICT_SW_SIZE;

// ta: 2,181 entries
extern const espyak_dict_entry_embedded_t DICT_TA[];
extern const size_t DICT_TA_SIZE;

// te: 1,793 entries
extern const espyak_dict_entry_embedded_t DICT_TE[];
extern const size_t DICT_TE_SIZE;

// th: 10 entries
extern const espyak_dict_entry_embedded_t DICT_TH[];
extern const size_t DICT_TH_SIZE;

// ti: 1,720 entries
extern const espyak_dict_entry_embedded_t DICT_TI[];
extern const size_t DICT_TI_SIZE;

// tk: 926 entries
extern const espyak_dict_entry_embedded_t DICT_TK[];
extern const size_t DICT_TK_SIZE;

// tn: 107 entries
extern const espyak_dict_entry_embedded_t DICT_TN[];
extern const size_t DICT_TN_SIZE;

// tr: 1,943 entries
extern const espyak_dict_entry_embedded_t DICT_TR[];
extern const size_t DICT_TR_SIZE;

// tt: 74 entries
extern const espyak_dict_entry_embedded_t DICT_TT[];
extern const size_t DICT_TT_SIZE;

// ug: 37 entries
extern const espyak_dict_entry_embedded_t DICT_UG[];
extern const size_t DICT_UG_SIZE;

// uk: 166 entries
extern const espyak_dict_entry_embedded_t DICT_UK[];
extern const size_t DICT_UK_SIZE;

// ur: 4,457 entries
extern const espyak_dict_entry_embedded_t DICT_UR[];
extern const size_t DICT_UR_SIZE;

// uz: 114 entries
extern const espyak_dict_entry_embedded_t DICT_UZ[];
extern const size_t DICT_UZ_SIZE;

// vi: 1,773 entries
extern const espyak_dict_entry_embedded_t DICT_VI[];
extern const size_t DICT_VI_SIZE;

// xex: 43 entries
extern const espyak_dict_entry_embedded_t DICT_XEX[];
extern const size_t DICT_XEX_SIZE;

// yue: 5,457 entries
extern const espyak_dict_entry_embedded_t DICT_YUE[];
extern const size_t DICT_YUE_SIZE;


/**
 * @brief Language lookup structure
 */
typedef struct {
    const char* code;
    const espyak_dict_entry_embedded_t* dict;
    const size_t size;
} espyak_language_dict_t;

/**
 * @brief All available language dictionaries
 */
extern const espyak_language_dict_t ESPYAK_ALL_LANGUAGES[];
extern const size_t ESPYAK_NUM_LANGUAGES;

#endif /* ESPYAK_ALL_LANGUAGES_H */
