/**
 * @file ba_dict.c
 * @brief Dictionary data for language: ba
 * 
 * Auto-generated by extract_all_languages.py
 * Source: espeak-ng dictsource/ba_*
 * 
 * Total entries: 70
 */

#include <stdint.h>

typedef struct {
    const char* word;
    const char* phonemes;
    uint32_t flags;
} espyak_dict_entry_embedded_t;

const espyak_dict_entry_embedded_t DICT_BA[70] = {
    {"_0", "n'ul?", 0},
    {"_0C", "j'WD", 0},
    {"_0M1", "m'eN", 0},
    {"_0M2", "milli'on", 0},
    {"_0M3", "milli'Ard", 0},
    {"_0M4", "billi'on", 0},
    {"_1", "b'er", 0},
    {"_1M2", "milli'on", 0},
    {"_1M3", "milli'Ard", 0},
    {"_1M4", "billi'on", 0},
    {"_1X", "'un", 0},
    {"_2", "ik'e", 0},
    {"_2X", "egerm'e", 0},
    {"_3", "'Ws", 0},
    {"_3X", "ut'VD", 0},
    {"_4", "d'yrt", 0},
    {"_4X", "qVr'q", 0},
    {"_5", "b'iS", 0},
    {"_5X", "ill'e", 0},
    {"_6", "Alt'V", 0},
    {"_6X", "Altm'VS", 0},
    {"_7", "et'e", 0},
    {"_7X", "etm'eS", 0},
    {"_8", "hig'eD", 0},
    {"_8X", "hikh'&n", 0},
    {"_9", "tug'VD", 0},
    {"_9X", "tukh'An", 0},
    {"_dpt", "_bWt,en", 0},
    {"а", "A:", 0},
    {"б", "be", 0},
    {"в", "we", 0},
    {"г", "ge", 0},
    {"д", "de", 0},
    {"е", "je", 0},
    {"ж", "Ze", 0},
    {"з", "ze", 0},
    {"и", "i", 0},
    {"й", "kVsk,A'i", 0},
    {"к", "kA", 0},
    {"л", "el", 0},
    {"м", "em", 0},
    {"н", "en", 0},
    {"о", "o:", 0},
    {"п", "pe", 0},
    {"р", "er", 0},
    {"с", "es", 0},
    {"т", "te", 0},
    {"у", "u", 0},
    {"ф", "ef", 0},
    {"х", "xA", 0},
    {"ц", "tse", 0},
    {"ч", "S;e", 0},
    {"ш", "SA", 0},
    {"щ", "SS;A", 0},
    {"ъ", "kAlVnl,Vqbilges'e", 0},
    {"ы", "V:", 0},
    {"ь", "neS;k&l,ekbilges'e", 0},
    {"э", "I|:", 0},
    {"ю", "ju", 0},
    {"я", "jA", 0},
    {"ё", "jo", 0},
    {"ғ", "Q\"e", 0},
    {"ҙ", "De", 0},
    {"ҡ", "qA", 0},
    {"ң", "eN", 0},
    {"ҫ", "eT", 0},
    {"ү", "y", 0},
    {"һ", "he", 0},
    {"ә", "&:", 0},
    {"ө", "W:", 0},
};

const size_t DICT_BA_SIZE = 70;
