/**
 * @file be_dict.c
 * @brief Dictionary data for language: be
 * 
 * Auto-generated by extract_all_languages.py
 * Source: espeak-ng dictsource/be_*
 * 
 * Total entries: 77
 */

#include <stdint.h>

typedef struct {
    const char* word;
    const char* phonemes;
    uint32_t flags;
} espyak_dict_entry_embedded_t;

const espyak_dict_entry_embedded_t DICT_BE[77] = {
    {"#", "exceptions", 0},
    {"_0", "n'ul;", 0},
    {"_0C", "st'O", 0},
    {"_0M1", "t'i\"s;ats.", 0},
    {"_0MA1", "t'i\"s;ats.i\"", 0},
    {"_1", "adz;'in", 0},
    {"_10", "dz;'Es;ats;", 0},
    {"_11", "adz;'inats:ats;", 0},
    {"_12", "dvan'ats:ats;", 0},
    {"_13", "tri\"n'ats:ats;", 0},
    {"_14", "ts.at'i\"rnats:ats;", 0},
    {"_15", "p;atn'ats:ats;", 0},
    {"_16", "s.asn'ats:ats;", 0},
    {"_17", "s;amn'ats:ats;", 0},
    {"_18", "vas;amn'ats:ats;", 0},
    {"_19", "dz;Ev;atn'ats:ats;", 0},
    {"_1MA1", "t'i\"s;ats.a", 0},
    {"_1f", "adna", 0},
    {"_2", "dv'a", 0},
    {"_2C", "dz;v;'Es;ts;E", 0},
    {"_2X", "dv'ats:ats;||", 0},
    {"_2f", "dz;v;'E", 0},
    {"_3", "tr'i\"", 0},
    {"_3C", "tr'i\"sta", 0},
    {"_3X", "tr'i\"ts:ats;||", 0},
    {"_4", "ts.at'i\"ri\"", 0},
    {"_4C", "ts.at'i\"ri\"sta", 0},
    {"_4X", "s'Orak||", 0},
    {"_5", "p;'ats;", 0},
    {"_5C", "p;ats;s'Ot", 0},
    {"_5X", "p;adz;:Es;'at||", 0},
    {"_6", "s.'Es;ts;", 0},
    {"_6C", "s.Es;ts;s'Ot", 0},
    {"_6X", "s.Ezdz;:Es;'at||", 0},
    {"_7", "s;'Em", 0},
    {"_7C", "s;Ems'Ot", 0},
    {"_7X", "s;'Emdz;Es;at||", 0},
    {"_8", "v'Os;Em", 0},
    {"_8C", "v,Os;Ems'Ot", 0},
    {"_8X", "v'Os;Emdz;Es;at||", 0},
    {"_9", "dz;'Ev;ats;", 0},
    {"_9C", "dz;Ev;ats;s'Ot", 0},
    {"_9X", "dz;Ev;an'Osta||", 0},
    {"а", "a", 0},
    {"б", "b", 0},
    {"в", "vE", 0},
    {"відзскі", "v;'itsk;i", 0},
    {"г", "QE", 0},
    {"д", "dE", 0},
    {"дождж", "d'Os.ts.", 0},
    {"е", "jE", 0},
    {"ж", "z.", 0},
    {"з", "z", 0},
    {"й", "i", 0},
    {"к", "ka", 0},
    {"л", "El", 0},
    {"м", "Em", 0},
    {"н", "En", 0},
    {"о", "O", 0},
    {"п", "pE", 0},
    {"р", "Er", 0},
    {"с", "Es", 0},
    {"т", "tE", 0},
    {"у", "u", 0},
    {"ф", "Ef", 0},
    {"х", "xa", 0},
    {"ц", "tsE", 0},
    {"ч", "ts.E", 0},
    {"ш", "s.a", 0},
    {"ы", "i\"", 0},
    {"ь", "m;'ak;:i||znak", 0},
    {"э", "E", 0},
    {"ю", "ju", 0},
    {"я", "ja", 0},
    {"ё", "jO", 0},
    {"і", "i", 0},
    {"ў", "w", 0},
};

const size_t DICT_BE_SIZE = 77;
