/**
 * @file grc_dict.c
 * @brief Dictionary data for language: grc
 * 
 * Auto-generated by extract_all_languages.py
 * Source: espeak-ng dictsource/grc_*
 * 
 * Total entries: 21
 */

#include <stdint.h>

typedef struct {
    const char* word;
    const char* phonemes;
    uint32_t flags;
} espyak_dict_entry_embedded_t;

const espyak_dict_entry_embedded_t DICT_GRC[21] = {
    {"?1", "_0lang", 0},
    {"ɦη", "$u", 0},
    {"ɦο", "$u", 0},
    {"αɦι", "$u", 0},
    {"οɦι", "$u", 0},
    {"ταὶν", "$u", 0},
    {"ταὶς", "$u", 0},
    {"τοὶν", "$u", 0},
    {"τοὶς", "$u", 0},
    {"τοὺ", "$u", 0},
    {"τοὺς", "$u", 0},
    {"τὰ", "$u", 0},
    {"τὰς", "$u", 0},
    {"τὴν", "$u", 0},
    {"τὴς", "$u", 0},
    {"τὸ", "$u", 0},
    {"τὸν", "$u", 0},
    {"τὼ", "$u", 0},
    {"τὼν", "$u", 0},
    {"τῂ", "$u", 0},
    {"τῲ", "$u", 0},
};

const size_t DICT_GRC_SIZE = 21;
