/**
 * @file hak_dict.c
 * @brief Dictionary data for language: hak
 * 
 * Auto-generated by extract_all_languages.py
 * Source: espeak-ng dictsource/hak_*
 * 
 * Total entries: 22
 */

#include <stdint.h>

typedef struct {
    const char* word;
    const char* phonemes;
    uint32_t flags;
} espyak_dict_entry_embedded_t;

const espyak_dict_entry_embedded_t DICT_HAK[22] = {
    {"_0", "laN2", 0},
    {"_0C", "pak5_|", 0},
    {"_0M1", "tS;hien1_|", 0},
    {"_0M2", "van4_|", 0},
    {"_1", "it5", 0},
    {"_1X", "S;i.6_|", 0},
    {"_2", "n^i4", 0},
    {"_2X", "Ni4S;i.6_|", 0},
    {"_3", "sam1", 0},
    {"_3X", "sam2S;i.6_|", 0},
    {"_4", "S;i4", 0},
    {"_4X", "S;i4S;i.6_|", 0},
    {"_5", "N-3", 0},
    {"_5X", "N-3S;i.6_|", 0},
    {"_6", "liuk5", 0},
    {"_6X", "liuk5S;i.6_|", 0},
    {"_7", "tS;hit5", 0},
    {"_7X", "tS;hit5S;i.6_|", 0},
    {"_8", "pat5", 0},
    {"_8X", "pat5S;i.6_|", 0},
    {"_9", "kiu3", 0},
    {"_9X", "kiu3S;i.6_|", 0},
};

const size_t DICT_HAK_SIZE = 22;
