/**
 * @file ht_dict.c
 * @brief Dictionary data for language: ht
 * 
 * Auto-generated by extract_all_languages.py
 * Source: espeak-ng dictsource/ht_*
 * 
 * Total entries: 50
 */

#include <stdint.h>

typedef struct {
    const char* word;
    const char* phonemes;
    uint32_t flags;
} espyak_dict_entry_embedded_t;

const espyak_dict_entry_embedded_t DICT_HT[50] = {
    {"_0", "zero", 0},
    {"_0C", "sA~", 0},
    {"_0M1", "mil", 0},
    {"_0M2", "miljO~", 0},
    {"_0M3", "miljar", 0},
    {"_0and", "e", 0},
    {"_1", "youn", 0},
    {"_10", "dis", 0},
    {"_11", "onz", 0},
    {"_12", "douz", 0},
    {"_13", "trez", 0},
    {"_14", "katoz", 0},
    {"_15", "kenz", 0},
    {"_16", "sez", 0},
    {"_17", "diset", 0},
    {"_18", "dizuit", 0},
    {"_19", "diznef", 0},
    {"_1C0", "sA~t2", 0},
    {"_1M1", "mil", 0},
    {"_2", "de", 0},
    {"_20", "ven", 0},
    {"_21", "venteyen", 0},
    {"_22", "vennde", 0},
    {"_23", "venntwa", 0},
    {"_24", "vennkat", 0},
    {"_25", "vennsenk", 0},
    {"_26", "vennsis", 0},
    {"_27", "vennset", 0},
    {"_28", "ventuit", 0},
    {"_29", "ventnef", 0},
    {"_3", "twa", 0},
    {"_30", "trant", 0},
    {"_4", "kat", 0},
    {"_40", "karan", 0},
    {"_5", "senk", 0},
    {"_50", "senkant", 0},
    {"_6", "sis", 0},
    {"_60", "swasant", 0},
    {"_7", "set", 0},
    {"_70", "swasanndis", 0},
    {"_8", "uit", 0},
    {"_80", "katr@vE~z2", 0},
    {"_9", "nef", 0},
    {"_dpt", "virgyl", 0},
    {"_roman", "rom'E~", 0},
    {"li", "$u", 0},
    {"mwen", "$u", 0},
    {"nou", "$u", 0},
    {"ou", "$u", 0},
    {"yo", "$u", 0},
};

const size_t DICT_HT_SIZE = 50;
