/**
 * @file io_dict.c
 * @brief Dictionary data for language: io
 * 
 * Auto-generated by extract_all_languages.py
 * Source: espeak-ng dictsource/io_*
 * 
 * Total entries: 50
 */

#include <stdint.h>

typedef struct {
    const char* word;
    const char* phonemes;
    uint32_t flags;
} espyak_dict_entry_embedded_t;

const espyak_dict_entry_embedded_t DICT_IO[50] = {
    {"Ago", "ag'osto", 0},
    {"Apr", "apR'ilo", 0},
    {"Dec", "dets'embRo", 0},
    {"Feb", "febRu'aRo", 0},
    {"Jan", "dZanu'aRo", 0},
    {"Jul", "dZ'ulio", 0},
    {"Jun", "dZ'unio", 0},
    {"Maj", "m'ajo", 0},
    {"Mar", "m'aRto", 0},
    {"Nov", "nov'embRo", 0},
    {"Okt", "okt'obRo", 0},
    {"Sept", "sept'embRo", 0},
    {"_!", "klamopunto", 0},
    {"_,", "komo", 0},
    {"_.", "punto", 0},
    {"_0", "zero", 0},
    {"_0C", "atsent", 0},
    {"_0M1", "a_m,il_", 0},
    {"_0M2", "mi'lion", 0},
    {"_0M3", "mili'ard", 0},
    {"_0M4", "bi'lion", 0},
    {"_0and", "_e_", 0},
    {"_1", "'un", 0},
    {"_1C", "ts'ent", 0},
    {"_1M1", "m'il_", 0},
    {"_1X", "d'ek", 0},
    {"_2", "d'u", 0},
    {"_2X", "d'uadek", 0},
    {"_3", "t@-r'i", 0},
    {"_3X", "t@-r'iadek", 0},
    {"_4", "ku'aR", 0},
    {"_4X", "ku'ar_adek", 0},
    {"_5", "k'in", 0},
    {"_5X", "k'inadek", 0},
    {"_6", "s'is", 0},
    {"_6X", "s'isadek", 0},
    {"_7", "s'ep", 0},
    {"_7X", "s'epadek", 0},
    {"_8", "'ok", 0},
    {"_8X", "'okadek", 0},
    {"_9", "n'on", 0},
    {"_9X", "n'onadek", 0},
    {"_:", "bipunto", 0},
    {"_;", "komopunto", 0},
    {"_?", "kuestionopunto", 0},
    {"_dpt", "_komo_", 0},
    {"ka", "$u", 0},
    {"kad", "$u", 0},
    {"la", "%la", 0},
    {"ne", "$u+", 0},
};

const size_t DICT_IO_SIZE = 50;
