/**
 * @file jbo_dict.c
 * @brief Dictionary data for language: jbo
 * 
 * Auto-generated by extract_all_languages.py
 * Source: espeak-ng dictsource/jbo_*
 * 
 * Total entries: 85
 */

#include <stdint.h>

typedef struct {
    const char* word;
    const char* phonemes;
    uint32_t flags;
} espyak_dict_entry_embedded_t;

const espyak_dict_entry_embedded_t DICT_JBO[85] = {
    {"_0", "no", 0},
    {"_1", "pa", 0},
    {"_2", "Re", 0},
    {"_3", "Si", 0},
    {"_4", "vo", 0},
    {"_5", "mu", 0},
    {"_6", "xa", 0},
    {"_7", "ze", 0},
    {"_8", "bi", 0},
    {"_9", "so", 0},
    {"_dpt", "pi_", 0},
    {"a", "$brk", 0},
    {"b", "b@", 0},
    {"ba'e", "$u+", 0},
    {"boi", "boI_:", 0},
    {"c", "S@", 0},
    {"cai", "S'aI__!", 0},
    {"ce'u", "$u+", 0},
    {"cu", "$brk", 0},
    {"cu'e", "S'uhe_!", 0},
    {"cu'i", "S'uhi_!", 0},
    {"d", "d@", 0},
    {"e", "$brk", 0},
    {"f", "f@", 0},
    {"g", "g@", 0},
    {"ge'u", "g,ehu_:", 0},
    {"gi", "$pause", 0},
    {"goi", "_;_goI", 0},
    {"h", "@h'@bu", 0},
    {"i", "__;__i", 0},
    {"ija", "_;__iZa", 0},
    {"ijanai", "_;__iZan'aI", 0},
    {"ije", "_;__iZe", 0},
    {"ije'i", "_;__iZehi", 0},
    {"ijenai", "_;__iZenaI", 0},
    {"ijo", "_;__iZo", 0},
    {"ijonai", "_;__iZon'aI", 0},
    {"inaja", "_;__inaZa", 0},
    {"j", "Z@", 0},
    {"ja", "$brk", 0},
    {"ja'a", "Z'aha_!", 0},
    {"je", "$brk", 0},
    {"ji", "$brk", 0},
    {"jo", "$brk", 0},
    {"jo'u", "$u+", 0},
    {"joi", "$brk", 0},
    {"ju", "$brk", 0},
    {"k", "k@", 0},
    {"ke'a", "$u+", 0},
    {"kei", "keI_::", 0},
    {"ku", "ku_:", 0},
    {"ku'o", "k,uho_::", 0},
    {"li'u", "l,ihu_::", 0},
    {"lu", "lu_:", 0},
    {"lu'u", "l,uhu_:", 0},
    {"ma", "m'a__", 0},
    {"mo", "m'o__", 0},
    {"na", "n'a__!", 0},
    {"nai", "n'aI__!", 0},
    {"no'u", "_;_nohu", 0},
    {"noi", "_;_noI", 0},
    {"o", "$brk", 0},
    {"p", "p@", 0},
    {"pei", "p'eI__!", 0},
    {"po'e", "$u+", 0},
    {"po'u", "_;_pohu", 0},
    {"poi", "_;_poI", 0},
    {"q", "k'@bu", 0},
    {"ru'e", "R'uhe_!", 0},
    {"s", "s@", 0},
    {"sai", "s'aI__!", 0},
    {"t", "t@", 0},
    {"to", "_::to", 0},
    {"toi", "toI_::", 0},
    {"tu'e", "t,uhe_:", 0},
    {"tu'u", "t,uhu_::", 0},
    {"u", "$brk", 0},
    {"v", "v@", 0},
    {"vau", "vaU_::", 0},
    {"w", "v'@bu", 0},
    {"x", "x@", 0},
    {"xo", "x'o__", 0},
    {"z", "z@", 0},
    {"za'e", "$u+", 0},
    {"zo'e", "$u+", 0},
};

const size_t DICT_JBO_SIZE = 85;
