/**
 * @file kaa_dict.c
 * @brief Dictionary data for language: kaa
 * 
 * Auto-generated by extract_all_languages.py
 * Source: espeak-ng dictsource/kaa_*
 * 
 * Total entries: 26
 */

#include <stdint.h>

typedef struct {
    const char* word;
    const char* phonemes;
    uint32_t flags;
} espyak_dict_entry_embedded_t;

const espyak_dict_entry_embedded_t DICT_KAA[26] = {
    {"_0", "n'Yl", 0},
    {"_0C", "Z'u#z", 0},
    {"_0M1", "m'@N", 0},
    {"_0M2", "m@jLL@j'on", 0},
    {"_0M3", "m@jLL@j'Ard", 0},
    {"_1", "b'Ir", 0},
    {"_1M2", "m@jLL@j'on", 0},
    {"_1M3", "m@jLL@j'Ard", 0},
    {"_1X", "'on", 0},
    {"_2", "j'ekI", 0},
    {"_2X", "Z@g@rm'A", 0},
    {"_3", "u#S", 0},
    {"_3X", "'ot@z", 0},
    {"_4", "t8rt", 0},
    {"_4X", "q'@r@q", 0},
    {"_5", "b'es", 0},
    {"_5X", "'eliw", 0},
    {"_6", "'Alt@", 0},
    {"_6X", "'ALp@s", 0},
    {"_7", "Z'etI", 0},
    {"_7X", "Zetp'Is", 0},
    {"_8", "s'egIz", 0},
    {"_8X", "seks'en", 0},
    {"_9", "t'oG@z", 0},
    {"_9X", "toqs'An", 0},
    {"_dpt", "_Z&n'e_", 0},
};

const size_t DICT_KAA_SIZE = 26;
