/**
 * @file kl_dict.c
 * @brief Dictionary data for language: kl
 * 
 * Auto-generated by extract_all_languages.py
 * Source: espeak-ng dictsource/kl_*
 * 
 * Total entries: 82
 */

#include <stdint.h>

typedef struct {
    const char* word;
    const char* phonemes;
    uint32_t flags;
} espyak_dict_entry_embedded_t;

const espyak_dict_entry_embedded_t DICT_KL[82] = {
    {"_0", "'nOl", 0},
    {"_0C", "h'un*@:D", 0},
    {"_0M1", "t'u:s@-n", 0},
    {"_0M2", "milij'o:nV", 0},
    {"_0M3", "milij'a:d3", 0},
    {"_0M4", "bilij'o:n3", 0},
    {"_0and", "V", 0},
    {"_1", "'en", 0},
    {"_10", "t'i", 0},
    {"_10o", "ti@n3", 0},
    {"_11", "'Elv@", 0},
    {"_11o", "Elfd3", 0},
    {"_12", "t'Vl", 0},
    {"_12o", "tVlfd3", 0},
    {"_13", "tR'&d@-n", 0},
    {"_14", "fj'ord@-n", 0},
    {"_15", "f'emt@-n", 0},
    {"_16", "s'ajsd@-n", 0},
    {"_17", "s'Wd@-n", 0},
    {"_18", "'&d@-n", 0},
    {"_19", "n'ed@-n", 0},
    {"_1C", "ed||h'unr@:D", 0},
    {"_1M1", "ed||t'u:s@-n", 0},
    {"_1M2", "'e:n||milij'o:n", 0},
    {"_1M3", "'e:n||milij'a:d", 0},
    {"_1M4", "'e:n||bilij'o:n", 0},
    {"_1o", "fWrsd3", 0},
    {"_2", "t'o", 0},
    {"_20", "inukn'a:l#uQu", 0},
    {"_2X", "t'y:w", 0},
    {"_2Xo", "t'yv@n@", 0},
    {"_2o", "&n@n", 0},
    {"_3", "tR'e", 0},
    {"_3X", "tR'&Dv@", 0},
    {"_3Xo", "tr'&ft@", 0},
    {"_3o", "trEdj3", 0},
    {"_4", "f'iV", 0},
    {"_4X", "f'W:V", 0},
    {"_4Xo", "fWV'tyv@n@", 0},
    {"_4o", "fjeV", 0},
    {"_5", "f'Em", 0},
    {"_5X", "h&l't*Es", 0},
    {"_5Xo", "h&lt*'Esenstyv@n@", 0},
    {"_5o", "fEmt3", 0},
    {"_6", "s'EQs", 0},
    {"_6X", "t*'Es", 0},
    {"_6Xo", "tr'Esenstyv@n@", 0},
    {"_6o", "sjEd3", 0},
    {"_7", "s'yw", 0},
    {"_7X", "h&lfj'&rs", 0},
    {"_7Xo", "h&lfj'&rsenstyv@n@", 0},
    {"_7o", "syvn3", 0},
    {"_8", "'O:d@", 0},
    {"_8X", "f'irs", 0},
    {"_8Xo", "firsenstyv@n@", 0},
    {"_8o", "Vtn3", 0},
    {"_9", "n'i", 0},
    {"_9X", "h&lf'Ems", 0},
    {"_9Xo", "h&lf'Emsenstyv@n@", 0},
    {"_9o", "ni@n3", 0},
    {"_dpt", "kom:a_", 0},
    {"_ord", "3", 0},
    {"b", "bE", 0},
    {"c", "sE", 0},
    {"d", "dE", 0},
    {"f", "Ef", 0},
    {"g", "ji", 0},
    {"h", "ha", 0},
    {"j", "jE", 0},
    {"k", "ka", 0},
    {"l", "El", 0},
    {"m", "Em", 0},
    {"n", "En", 0},
    {"p", "pE", 0},
    {"q", "qa", 0},
    {"r", "Er", 0},
    {"s", "Es", 0},
    {"t", "tE", 0},
    {"v", "vE", 0},
    {"w", "wE", 0},
    {"x", "iks", 0},
    {"z", "zE", 0},
};

const size_t DICT_KL_SIZE = 82;
