/**
 * @file mi_dict.c
 * @brief Dictionary data for language: mi
 * 
 * Auto-generated by extract_all_languages.py
 * Source: espeak-ng dictsource/mi_*
 * 
 * Total entries: 14
 */

#include <stdint.h>

typedef struct {
    const char* word;
    const char* phonemes;
    uint32_t flags;
} espyak_dict_entry_embedded_t;

const espyak_dict_entry_embedded_t DICT_MI[14] = {
    {"_0", "kORe", 0},
    {"_1", "tahi", 0},
    {"_2", "Rua", 0},
    {"_3", "tORu", 0},
    {"_4", "fa:", 0},
    {"_5", "Rima", 0},
    {"_6", "ono", 0},
    {"_7", "fitu", 0},
    {"_8", "waRu", 0},
    {"_9", "iwa", 0},
    {"kōrero", "$1", 0},
    {"raru", "'ra_ru", 0},
    {"raruraru", "'ra_ru_:ra_ru", 0},
    {"urupā", "u_rupa:", 0},
};

const size_t DICT_MI_SIZE = 14;
