/**
 * @file nci_dict.c
 * @brief Dictionary data for language: nci
 * 
 * Auto-generated by extract_all_languages.py
 * Source: espeak-ng dictsource/nci_*
 * 
 * Total entries: 16
 */

#include <stdint.h>

typedef struct {
    const char* word;
    const char* phonemes;
    uint32_t flags;
} espyak_dict_entry_embedded_t;

const espyak_dict_entry_embedded_t DICT_NCI[16] = {
    {"_0", "a?tle", 0},
    {"_1", "se:", 0},
    {"_10", "ma?tlaktli", 0},
    {"_1X", "ma?tlaktlion", 0},
    {"_2", "O:me", 0},
    {"_20", "sempO:walli", 0},
    {"_2X", "sempO:wallion", 0},
    {"_3", "e:ji", 0},
    {"_30", "sempO:walliomma?tlaktli", 0},
    {"_3X", "sempO:walliomma?tlaktlion", 0},
    {"_4", "na:wi", 0},
    {"_5", "ma:kwi:lli", 0},
    {"_6", "tSikwase:", 0},
    {"_7", "tSicO:me", 0},
    {"_8", "tSiwke:ji", 0},
    {"_9", "tSiwkna:wi", 0},
};

const size_t DICT_NCI_SIZE = 16;
