/**
 * @file nog_dict.c
 * @brief Dictionary data for language: nog
 * 
 * Auto-generated by extract_all_languages.py
 * Source: espeak-ng dictsource/nog_*
 * 
 * Total entries: 37
 */

#include <stdint.h>

typedef struct {
    const char* word;
    const char* phonemes;
    uint32_t flags;
} espyak_dict_entry_embedded_t;

const espyak_dict_entry_embedded_t DICT_NOG[37] = {
    {"_0", "n'ol?", 0},
    {"_0C", "j'uz", 0},
    {"_0M1", "m'@N", 0},
    {"_0M2", "mILl'Ion", 0},
    {"_0M3", "mILl'IARd", 0},
    {"_1", "b'IR", 0},
    {"_1X", "'on", 0},
    {"_2", "'ekI", 0},
    {"_2X", "j@Rm'A", 0},
    {"_3", "'u#S", 0},
    {"_3X", "'ot@z", 0},
    {"_4", "d'8Rt", 0},
    {"_4X", "k'@Rk", 0},
    {"_5", "b'es", 0},
    {"_5X", "j'eLlI", 0},
    {"_6", "'Alt@", 0},
    {"_6X", "'Alp@s", 0},
    {"_7", "j'etI", 0},
    {"_7X", "j'etpIs", 0},
    {"_8", "s'egIz", 0},
    {"_8X", "s'eksen", 0},
    {"_9", "t'oG@z", 0},
    {"_9X", "t'oqsAn", 0},
    {"ама", "$1", 0},
    {"ба", "$u", 0},
    {"бе", "$u", 0},
    {"бен", "$u", 0},
    {"книга", "_^_RU", 0},
    {"компания", "_^_RU", 0},
    {"конверт", "_^_RU", 0},
    {"ма", "$u", 0},
    {"ме", "$u", 0},
    {"ногай", "$2", 0},
    {"па", "$u", 0},
    {"пе", "$u", 0},
    {"пен", "$u", 0},
    {"эм", "$u", 0},
};

const size_t DICT_NOG_SIZE = 37;
