/**
 * @file om_dict.c
 * @brief Dictionary data for language: om
 * 
 * Auto-generated by extract_all_languages.py
 * Source: espeak-ng dictsource/om_*
 * 
 * Total entries: 85
 */

#include <stdint.h>

typedef struct {
    const char* word;
    const char* phonemes;
    uint32_t flags;
} espyak_dict_entry_embedded_t;

const espyak_dict_entry_embedded_t DICT_OM[85] = {
    {"%", "parsanti", 0},
    {"*", "astariiksii", 0},
    {"+", "ida'u:", 0},
    {"=", "qixedha", 0},
    {"?!3", "_0and", 0},
    {"_$", "dollari:", 0},
    {"_%", "parsanti", 0},
    {"_&", "fi", 0},
    {"_-", "hir'isu", 0},
    {"_.", "xuqaa", 0},
    {"_0", "duw:a:", 0},
    {"_0C", "ib:'a", 0},
    {"_0M1", "kuma", 0},
    {"_0M2", "milijoni:", 0},
    {"_0M3", "bilijoni:", 0},
    {"_1", "tok:o", 0},
    {"_10", "kud'an", 0},
    {"_1C", "ib:'atokko", 0},
    {"_1X", "kud'a", 0},
    {"_2", "lama", 0},
    {"_20", "dig'dama", 0},
    {"_2C", "ib:'alama", 0},
    {"_2X", "dig'dami:", 0},
    {"_3", "sadi:", 0},
    {"_3C", "ib:'asadi", 0},
    {"_3X", "sod:omi:", 0},
    {"_4", "afur", 0},
    {"_4C", "ib:'a:furi", 0},
    {"_4X", "afurtami:", 0},
    {"_5", "S'an", 0},
    {"_5C", "ib:'a:Sani", 0},
    {"_5X", "Santami:", 0},
    {"_6", "dZ'a:ha", 0},
    {"_6C", "ib:'adZa", 0},
    {"_6X", "dZatami:x", 0},
    {"_7", "To:rba", 0},
    {"_7C", "ib:'atorba", 0},
    {"_7X", "torbat:ami:", 0},
    {"_8", "sad:e:t", 0},
    {"_8C", "ib:'asade:ti:", 0},
    {"_8X", "sade:t:ami:", 0},
    {"_9", "sagal", 0},
    {"_9C", "ib:'asagali", 0},
    {"_9X", "sagal't:ami:", 0},
    {"_<", "nixiqata", 0},
    {"_>", "nica:la", 0},
    {"_?", "mal:ato:ga:f:i:", 0},
    {"_dpt", "tuqa:", 0},
    {"_roman", "roma:ni:", 0},
    {"a", "a:", 0},
    {"b", "ba:", 0},
    {"c", "tS`a:", 0},
    {"ch", "tSa:", 0},
    {"d", "da:", 0},
    {"dh", "Da:", 0},
    {"e", "e:", 0},
    {"f", "fa:", 0},
    {"g", "ga:", 0},
    {"h", "ha:", 0},
    {"i", "i:", 0},
    {"j", "ja:", 0},
    {"k", "ka:", 0},
    {"l", "la:", 0},
    {"m", "ma:", 0},
    {"n", "na", 0},
    {"ny", "n^a:", 0},
    {"o", "o:", 0},
    {"p", "pa:", 0},
    {"ph", "Pa:", 0},
    {"q", "k`a:", 0},
    {"r", "ra:", 0},
    {"s", "sa:", 0},
    {"sh", "Sa:", 0},
    {"t", "ta:", 0},
    {"ts", "tsa:", 0},
    {"u", "u:", 0},
    {"v", "va:", 0},
    {"w", "wa:", 0},
    {"x", "t`a:", 0},
    {"y", "ya:", 0},
    {"z", "za:", 0},
    {"zy", "Za:", 0},
    {"£", "pawundi", 0},
    {"µ", "ma:ykro", 0},
    {"€", "yuuroo", 0},
};

const size_t DICT_OM_SIZE = 85;
