/**
 * @file pap_dict.c
 * @brief Dictionary data for language: pap
 * 
 * Auto-generated by extract_all_languages.py
 * Source: espeak-ng dictsource/pap_*
 * 
 * Total entries: 83
 */

#include <stdint.h>

typedef struct {
    const char* word;
    const char* phonemes;
    uint32_t flags;
} espyak_dict_entry_embedded_t;

const espyak_dict_entry_embedded_t DICT_PAP[83] = {
    {"_0", "z'eRo", 0},
    {"_0C", "sj'en", 0},
    {"_0M1", "m'il", 0},
    {"_0M2", "mi'on", 0},
    {"_1", "'unu", 0},
    {"_11", "djes'un", 0},
    {"_1X", "dj'es", 0},
    {"_2", "d'os", 0},
    {"_2X", "b'inti", 0},
    {"_3", "tR'es", 0},
    {"_3X", "tR'inta", 0},
    {"_4", "kwat'eR", 0},
    {"_4X", "kwaR'enta", 0},
    {"_5", "s'inku", 0},
    {"_5X", "sinkw'enta", 0},
    {"_6", "s'Ejs", 0},
    {"_6X", "ses'enta", 0},
    {"_7", "S'ete", 0},
    {"_7X", "set'enta", 0},
    {"_8", "'otSo", 0},
    {"_8X", "otS'enta", 0},
    {"_9", "nw'ebe", 0},
    {"_9X", "nob'enta", 0},
    {"_a", "a", 0},
    {"_acu", "skERpi", 0},
    {"_dpt", "_kOma/", 0},
    {"_e", "e", 0},
    {"_grv", "gRave", 0},
    {"_i", "i", 0},
    {"_o", "o", 0},
    {"_y", "igR'Ek", 0},
    {"a", "$u+", 0},
    {"abo", "$u+", 0},
    {"algun", "$u+", 0},
    {"ami", "$u+", 0},
    {"b", "be", 0},
    {"bo", "$u+", 0},
    {"boso", "$u+", 0},
    {"c", "se", 0},
    {"d", "de", 0},
    {"den", "$u+", 0},
    {"di", "$u+", 0},
    {"e", "$u+", 0},
    {"el", "$u+", 0},
    {"f", "Ef", 0},
    {"g", "ge", 0},
    {"h", "ha", 0},
    {"i", "$u+", 0},
    {"j", "je", 0},
    {"k", "ka", 0},
    {"ku", "$u+", 0},
    {"l", "El", 0},
    {"lo", "$u+", 0},
    {"m", "Em", 0},
    {"ma", "$pause", 0},
    {"mi", "$u+", 0},
    {"n", "En", 0},
    {"na", "$u+", 0},
    {"nan", "$u+", 0},
    {"nos", "$u+", 0},
    {"o", "$u+", 0},
    {"p", "pe", 0},
    {"por", "$u+", 0},
    {"q", "ky", 0},
    {"r", "ER", 0},
    {"s", "Es", 0},
    {"su", "$u+", 0},
    {"t", "te", 0},
    {"ta", "$u+", 0},
    {"tabata", "$u+", 0},
    {"un", "$u+", 0},
    {"v", "ve", 0},
    {"w", "we", 0},
    {"x", "Eks", 0},
    {"y", "igR'Ek", 0},
    {"z", "zEt", 0},
    {"á", "$accent", 0},
    {"é", "$accent", 0},
    {"í", "$accent", 0},
    {"ñ", "en^e", 0},
    {"òf", "$u+", 0},
    {"ó", "$accent", 0},
    {"ú", "$accent", 0},
};

const size_t DICT_PAP_SIZE = 83;
