/**
 * @file qu_dict.c
 * @brief Dictionary data for language: qu
 * 
 * Auto-generated by extract_all_languages.py
 * Source: espeak-ng dictsource/qu_*
 * 
 * Total entries: 76
 */

#include <stdint.h>

typedef struct {
    const char* word;
    const char* phonemes;
    uint32_t flags;
} espyak_dict_entry_embedded_t;

const espyak_dict_entry_embedded_t DICT_QU[76] = {
    {"_0", "tS?usak", 0},
    {"_0C", "patSak", 0},
    {"_0M1", "waranka", 0},
    {"_0M2", "hunu", 0},
    {"_0M3", "l^una", 0},
    {"_1", "huk", 0},
    {"_10", "tSunka", 0},
    {"_2", "iskaj", 0},
    {"_3", "kimsa", 0},
    {"_4", "tawa", 0},
    {"_5", "pitSka", 0},
    {"_6", "sukta", 0},
    {"_7", "kantSis", 0},
    {"_8", "pusak", 0},
    {"_9", "iskun", 0},
    {"a", "a:", 0},
    {"b", "ba:", 0},
    {"c", "tsa:", 0},
    {"ch", "tSa:", 0},
    {"ch'", "tS?a:", 0},
    {"chh", "tSha:", 0},
    {"d", "da:", 0},
    {"e", "e:", 0},
    {"f", "fa:", 0},
    {"g", "ga:", 0},
    {"h", "ha:", 0},
    {"hayk'a", "$u", 0},
    {"i", "i:", 0},
    {"ima", "$u", 0},
    {"imahina", "$u", 0},
    {"imapas", "$u", 0},
    {"imayna", "$u", 0},
    {"j", "xa:", 0},
    {"k", "ka:", 0},
    {"k'", "k`?a:", 0},
    {"kay", "$u", 0},
    {"kh", "kha:", 0},
    {"kikin", "$u", 0},
    {"l", "la:", 0},
    {"ll", "l^a:", 0},
    {"llapan", "$u", 0},
    {"m", "ma:", 0},
    {"machka", "$u", 0},
    {"may", "$u", 0},
    {"n", "na:", 0},
    {"nuqa", "$u", 0},
    {"o", "o:", 0},
    {"p", "pa:", 0},
    {"p'", "p?a:", 0},
    {"pacha", "$u", 0},
    {"pay", "$u", 0},
    {"paykuna", "$u", 0},
    {"ph", "pha:", 0},
    {"pi", "$u", 0},
    {"q", "ka:", 0},
    {"q'", "k?a:", 0},
    {"qam", "$u", 0},
    {"qamkuna", "$u", 0},
    {"qh", "kha:", 0},
    {"r", "RRa:", 0},
    {"s", "sa:", 0},
    {"sapay", "$u", 0},
    {"t", "ta:", 0},
    {"t'", "t?a", 0},
    {"th", "tha:", 0},
    {"tukuy", "$u", 0},
    {"u", "u:", 0},
    {"v", "va:", 0},
    {"w", "wa:", 0},
    {"x", "ksa:", 0},
    {"y", "ja:", 0},
    {"z", "za:", 0},
    {"ñ", "n^a:", 0},
    {"ñuqa", "$u", 0},
    {"ñuqanchik", "$u", 0},
    {"ñuqayku", "$u", 0},
};

const size_t DICT_QU_SIZE = 76;
