/**
 * @file quc_dict.c
 * @brief Dictionary data for language: quc
 * 
 * Auto-generated by extract_all_languages.py
 * Source: espeak-ng dictsource/quc_*
 * 
 * Total entries: 10
 */

#include <stdint.h>

typedef struct {
    const char* word;
    const char* phonemes;
    uint32_t flags;
} espyak_dict_entry_embedded_t;

const espyak_dict_entry_embedded_t DICT_QUC[10] = {
    {"_1", "jun", 0},
    {"_10", "lajuj", 0},
    {"_2", "keb'", 0},
    {"_3", "oxib'", 0},
    {"_4", "kajib'", 0},
    {"_5", "job'", 0},
    {"_6", "waqib'", 0},
    {"_7", "wuqub'", 0},
    {"_8", "wajxaqib'", 0},
    {"_9", "b'elejeb'", 0},
};

const size_t DICT_QUC_SIZE = 10;
