/**
 * @file qya_dict.c
 * @brief Dictionary data for language: qya
 * 
 * Auto-generated by extract_all_languages.py
 * Source: espeak-ng dictsource/qya_*
 * 
 * Total entries: 38
 */

#include <stdint.h>

typedef struct {
    const char* word;
    const char* phonemes;
    uint32_t flags;
} espyak_dict_entry_embedded_t;

const espyak_dict_entry_embedded_t DICT_QYA[38] = {
    {"_0", "_!", 0},
    {"_1", "m'inE", 0},
    {"_10", "kw'aIn", 0},
    {"_2", "'at:a", 0},
    {"_3", "n'EldE", 0},
    {"_4", "k'anta", 0},
    {"_5", "l'Empe", 0},
    {"_6", "'EnkwE", 0},
    {"_7", "'otso", 0},
    {"_8", "t'olto", 0},
    {"_9", "n'ErtE", 0},
    {"a", "$u", 0},
    {"an", "$u", 0},
    {"ar", "$u", 0},
    {"et", "$u", 0},
    {"han", "$u", 0},
    {"ho", "$u", 0},
    {"hya", "$u", 0},
    {"i", "$u", 0},
    {"lo", "$u", 0},
    {"mal", "$u", 0},
    {"mi", "$u", 0},
    {"mil", "$u", 0},
    {"nan", "$u", 0},
    {"no", "$u", 0},
    {"nu", "$u", 0},
    {"o", "$u", 0},
    {"or", "$u", 0},
    {"pa", "$u", 0},
    {"po", "$u", 0},
    {"qui", "$u", 0},
    {"ta", "$u", 0},
    {"tar", "$u", 0},
    {"ter", "$u", 0},
    {"va", "$u", 0},
    {"var", "$u", 0},
    {"ve", "$u", 0},
    {"yo", "$u", 0},
};

const size_t DICT_QYA_SIZE = 38;
