/**
 * @file sjn_dict.c
 * @brief Dictionary data for language: sjn
 * 
 * Auto-generated by extract_all_languages.py
 * Source: espeak-ng dictsource/sjn_*
 * 
 * Total entries: 21
 */

#include <stdint.h>

typedef struct {
    const char* word;
    const char* phonemes;
    uint32_t flags;
} espyak_dict_entry_embedded_t;

const espyak_dict_entry_embedded_t DICT_SJN[21] = {
    {"ach", "$u", 0},
    {"ah", "$u", 0},
    {"am", "$u", 0},
    {"an", "$u", 0},
    {"ben", "$u", 0},
    {"bo", "$u", 0},
    {"dan", "$u", 0},
    {"imladris", "$1", 0},
    {"ir", "$u", 0},
    {"menegroþ", "$1", 0},
    {"na", "$u", 0},
    {"nargoþrond", "$1", 0},
    {"ned", "$u", 0},
    {"nef", "$u", 0},
    {"nu", "$u", 0},
    {"o", "$u", 0},
    {"or", "$u", 0},
    {"os", "$u", 0},
    {"pen", "$u", 0},
    {"sui", "$u", 0},
    {"vi", "$u", 0},
};

const size_t DICT_SJN_SIZE = 21;
