/**
 * @file th_dict.c
 * @brief Dictionary data for language: th
 * 
 * Auto-generated by extract_all_languages.py
 * Source: espeak-ng dictsource/th_*
 * 
 * Total entries: 10
 */

#include <stdint.h>

typedef struct {
    const char* word;
    const char* phonemes;
    uint32_t flags;
} espyak_dict_entry_embedded_t;

const espyak_dict_entry_embedded_t DICT_TH[10] = {
    {"_0", "s3un", 0},
    {"_1", "n5ueng", 0},
    {"_2", "s5ong", 0},
    {"_3", "s3am", 0},
    {"_4", "s5i", 0},
    {"_5", "h3a", 0},
    {"_6", "h3ok", 0},
    {"_7", "ch3et", 0},
    {"_8", "p3aet", 0},
    {"_9", "k5ao", 0},
};

const size_t DICT_TH_SIZE = 10;
