/**
 * @file ug_dict.c
 * @brief Dictionary data for language: ug
 * 
 * Auto-generated by extract_all_languages.py
 * Source: espeak-ng dictsource/ug_*
 * 
 * Total entries: 37
 */

#include <stdint.h>

typedef struct {
    const char* word;
    const char* phonemes;
    uint32_t flags;
} espyak_dict_entry_embedded_t;

const espyak_dict_entry_embedded_t DICT_UG[37] = {
    {"_0", "n'Wl", 0},
    {"_0C", "j'yz", 0},
    {"_0M1", "m'IN", 0},
    {"_0M2", "mIll'Ijon", 0},
    {"_0M3", "mill'Ijard", 0},
    {"_0M4", "bIll'Ijon", 0},
    {"_1", "b'Ir", 0},
    {"_1C", "b'Irj'yz", 0},
    {"_1M2", "mIll'Ijon", 0},
    {"_1M3", "mill'Ijard", 0},
    {"_1M4", "bIll'Ijon", 0},
    {"_1X", "'on", 0},
    {"_2", "'IkkI", 0},
    {"_2C", "'IkkIj'yz", 0},
    {"_2X", "jIg'IRm&", 0},
    {"_3", "'ytS", 0},
    {"_3C", "'ytsj'yz", 0},
    {"_3X", "otuz", 0},
    {"_4", "t'Wt", 0},
    {"_4C", "t'Wtj'yz", 0},
    {"_4X", "k'Irk", 0},
    {"_5", "b'&S", 0},
    {"_5C", "b'&Sj'yz", 0},
    {"_5X", "'&luk", 0},
    {"_6", "'Alt&", 0},
    {"_6C", "'Alt&j'uz", 0},
    {"_6X", "'AtmIS", 0},
    {"_7", "j'&tta", 0},
    {"_7C", "j'&tt&j'yz", 0},
    {"_7X", "j'&tmIS", 0},
    {"_8", "s'&kkIz", 0},
    {"_8C", "s'&kkizj'yz", 0},
    {"_8X", "s'&ks&n", 0},
    {"_9", "t'oqquz", 0},
    {"_9C", "t'oqquzj'uz", 0},
    {"_9X", "t'okson", 0},
    {"_dpt", "p'&S", 0},
};

const size_t DICT_UG_SIZE = 37;
