/**
 * @file xex_dict.c
 * @brief Dictionary data for language: xex
 * 
 * Auto-generated by extract_all_languages.py
 * Source: espeak-ng dictsource/xex_*
 * 
 * Total entries: 43
 */

#include <stdint.h>

typedef struct {
    const char* word;
    const char* phonemes;
    uint32_t flags;
} espyak_dict_entry_embedded_t;

const espyak_dict_entry_embedded_t DICT_XEX[43] = {
    {"_0", "n%u", 0},
    {"_1", "n%E", 0},
    {"_2", "dw%o", 0},
    {"_3", "tj%E", 0},
    {"_4", "kw%a", 0},
    {"_5", "p%eI", 0},
    {"_6", "lj%o", 0},
    {"_7", "Z%aI", 0},
    {"_8", "bw%i", 0},
    {"_9", "gj%u", 0},
    {"_a", "áfa", 0},
    {"_dpt", "Z%ew", 0},
    {"_e", "éte", 0},
    {"_i", "íki", 0},
    {"_o", "óno", 0},
    {"_u", "úbu", 0},
    {"_y", "ýbu", 0},
    {"b", "bábon", 0},
    {"c", "xúxut", 0},
    {"d", "dódin", 0},
    {"f", "féfel", 0},
    {"g", "gúguk", 0},
    {"gu", "g%u:_", 0},
    {"h", "háflu", 0},
    {"j", "íki", 0},
    {"k", "kúkan", 0},
    {"ku", "k%u:_:", 0},
    {"l", "lélon", 0},
    {"lau", "l%aU_:", 0},
    {"lou", "l%ow_:", 0},
    {"m", "máspa", 0},
    {"n", "nínep", 0},
    {"p", "pópel", 0},
    {"q", "qáqip", 0},
    {"r", "réxti", 0},
    {"s", "sásek", 0},
    {"t", "tótot", 0},
    {"v", "vévet", 0},
    {"vu", "_:v%u:_:", 0},
    {"w", "úbu", 0},
    {"x", "xúxut", 0},
    {"y", "$brk", 0},
    {"z", "zózot", 0},
};

const size_t DICT_XEX_SIZE = 43;
